"""Campaign orchestration primitives."""

from fssr_nam.campaign.r1 import (
    CAMPAIGN_VERSION,
    CONFIRMATORY_RUN_CAP,
    DIAGNOSTIC_STAGE_CAPS,
    R1AuthorizationError,
    R1CampaignError,
    R1ConfigError,
    R1Executor,
    R1RunReuseError,
    RunSpec,
    expand_confirmatory_conditions,
    expand_stage,
    gate_requirements,
    load_gate_decisions,
    make_run_id,
    parse_run_id,
    validate_confirmatory_lock,
    validate_gate_authorization,
    validate_protocol_config,
    validate_repository_configs,
    validate_stage_config,
)

__all__ = [
    "CAMPAIGN_VERSION",
    "CONFIRMATORY_RUN_CAP",
    "DIAGNOSTIC_STAGE_CAPS",
    "R1AuthorizationError",
    "R1CampaignError",
    "R1ConfigError",
    "R1Executor",
    "R1RunReuseError",
    "RunSpec",
    "expand_confirmatory_conditions",
    "expand_stage",
    "gate_requirements",
    "load_gate_decisions",
    "make_run_id",
    "parse_run_id",
    "validate_confirmatory_lock",
    "validate_gate_authorization",
    "validate_protocol_config",
    "validate_repository_configs",
    "validate_stage_config",
]
